apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-bootstrap
  namespace: argocd
  finalizers:
  # Deletes apps if this CR is deleted
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/mcastellin/kind-lab.git'
    targetRevision: HEAD
    path: bootstrap
    helm:
      parameters:
      - name: awsAccountId
        value: "${AWS_ACCOUNT_ID}"
      - name: irsaRoleArn
        value: "${IRSA_ROLE_ARN}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
