apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
- namespace.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.28/samples/bookinfo/platform/kube/bookinfo.yaml
- networking.yaml
- serviceaccount.yaml

patches:
- path: patch-details-irsa.yaml
